"""empty message

Revision ID: 4dfbcdda5aca
Revises: 324a1a0ecb66
Create Date: 2022-08-24 01:34:57.578068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfbcdda5aca'
down_revision = '324a1a0ecb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map', 'user_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('map', 'tileinventory_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.create_foreign_key(None, 'map', 'tileinventory', ['tileinventory_id'], ['id'])
    op.create_foreign_key(None, 'map', 'user', ['user_id'], ['id'])
    op.add_column('tileinventory', sa.Column('width', sa.String(length=80), nullable=False))
    op.add_column('tileinventory', sa.Column('length', sa.String(length=80), nullable=False))
    op.add_column('tileinventory', sa.Column('quantity', sa.String(length=80), nullable=False))
    op.alter_column('tileinventory', 'user_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('tileinventory', 'tiles_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.create_foreign_key(None, 'tileinventory', 'tiles', ['tiles_id'], ['id'])
    op.create_foreign_key(None, 'tileinventory', 'user', ['user_id'], ['id'])
    op.drop_column('tiles', 'quantity')
    op.drop_column('tiles', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiles', sa.Column('size', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('tiles', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tileinventory', type_='foreignkey')
    op.drop_constraint(None, 'tileinventory', type_='foreignkey')
    op.alter_column('tileinventory', 'tiles_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('tileinventory', 'user_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('tileinventory', 'quantity')
    op.drop_column('tileinventory', 'length')
    op.drop_column('tileinventory', 'width')
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.alter_column('map', 'tileinventory_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('map', 'user_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
